const $=id=>document.getElementById(id);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=d=>d?new Date(d).toLocaleString('pl-PL',{timeZone:'Europe/Warsaw'}):'—';
const num=x=>x===null||x===undefined?'—':Number(x).toLocaleString('pl-PL',{maximumFractionDigits:2});
let current;
async function api(path,data){const r=await fetch('/api/'+path,{method:data===undefined?'GET':'POST',headers:{'X-TCOG-Pilot':'1',...(data===undefined?{}:{'Content-Type':'application/json'})},body:data===undefined?undefined:JSON.stringify(data),signal:AbortSignal.timeout(45000)});const body=await r.json();if(!r.ok){if(r.status===401)showLogin();throw Error(body.error||'Nie udało się wykonać operacji.');}return body;}
function showLogin(){$('login').hidden=false;$('workspace').hidden=true;$('logout').hidden=true;}
async function action(fn){$('notice').textContent='';try{await fn();}catch(e){$('notice').textContent=e.name==='TimeoutError'?'Przekroczono czas oczekiwania. Sprawdź stan przed ponowieniem zapisu.':e.message;}}
function render(s){current=s;$('login').hidden=true;$('workspace').hidden=false;$('logout').hidden=false;$('vehicleSetup').hidden=!!s.vehicle;$('working').hidden=!s.vehicle;$('vehicleTitle').textContent=s.vehicle?(s.vehicle.plate_number||s.vehicle.name||s.vehicle.device_id):'Wybierz pojazd';$('syncState').textContent=s.lastError||(s.busy?'Pobieranie danych…':'Automatyczne pobieranie aktywne dla zleceń bez pauzy.');
 $('orders').innerHTML=s.orders.length?s.orders.slice().reverse().map(o=>{const a=o.analysis;const row=(name,p)=>`<tr><td>${name}</td><td>${date(p?.date)}</td><td>${num(p?.odometer_can_km)}</td><td>${num(p?.odometer_gps_km)}</td></tr>`;return `<article><div class="heading"><h3>${escape(o.reference)}</h3><span class="status">${o.paused?'Wstrzymane':escape(a.status)}</span></div><p class="help">${escape(o.load.address)} → ${escape(o.unload.address)}</p><div class="metrics"><div class="metric"><span>Od wyjazdu do rozładunku</span><strong>${num(a.km)} km</strong><span>${a.source?'Licznik '+a.source:'Brak pełnego odcinka'}</span></div><div class="metric"><span>Przychód</span><strong>${num(o.revenue)} ${escape(o.currency)}</strong><span>${num(a.revenue_per_km)} ${escape(o.currency)}/km</span></div><div class="metric"><span>Zużycie paliwa z CAN</span><strong>${num(a.fuel_l)} l</strong><span>${num(a.litres_per_100km)} l/100 km</span></div></div><div class="tablewrap"><table><thead><tr><th>Zdarzenie</th><th>Czas (Polska)</th><th>CAN km</th><th>GPS km</th></tr></thead><tbody>${row('Postój na załadunku',a.load?.arrival)}${row('Wyjazd ze strefy',a.load?.departure)}${row('Postój na rozładunku',a.unload?.arrival)}${row('Wyjazd ze strefy',a.unload?.departure)}</tbody></table></div><p class="help">${a.sample_count} próbek · Pobrano do: ${date(new Date(o.cursor).toISOString())} · Ostatni zapis: ${date(o.lastSync)}</p><ul>${a.warnings.map(w=>`<li>${escape(w)}</li>`).join('')}</ul><p class="help">Przychód/km nie jest rentownością. Koszty nie są jeszcze uwzględnione.</p><div class="actions"><button data-plan="${o.id}">Pobierz plan dla kierowcy</button><button data-pause="${o.id}">${o.paused?'Wznów pobieranie':'Wstrzymaj pobieranie'}</button></div></article>`;}).join(''):'<p>Dodaj pierwsze zlecenie. Tutaj pojawią się odczyty z DBK.</p>';
}
function download(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('loginForm').onsubmit=e=>{e.preventDefault();action(async()=>{await api('login',{password:new FormData(e.target).get('password')});e.target.reset();render(await api('state'));});};
$('logout').onclick=()=>action(async()=>{await api('logout',{});current=null;showLogin();});
$('loadVehicles').onclick=()=>action(async()=>{$('loadVehicles').disabled=true;try{const {vehicles}=await api('vehicles');$('vehicles').replaceChildren(...vehicles.map(v=>new Option(v.plate_number||v.name||v.device_id,v.device_id)));$('vehicleForm').hidden=!vehicles.length;if(!vehicles.length)throw Error('Brak pojazdów z dostępem do historii.');}finally{$('loadVehicles').disabled=false;}});
$('vehicleForm').onsubmit=e=>{e.preventDefault();action(async()=>render(await api('vehicle',{device_id:$('vehicles').value})));};
$('orderForm').onsubmit=e=>{e.preventDefault();action(async()=>{const form=e.target,f=Object.fromEntries(new FormData(form));const stop=p=>({address:f[p+'Address'],lat:Number(f[p+'Lat']),lng:Number(f[p+'Lng']),radius:Number(f[p+'Radius'])});const button=form.querySelector('button');button.disabled=true;try{render(await api('orders',{reference:f.reference,revenue:Number(f.revenue),currency:f.currency,start:new Date(f.start).toISOString(),end:new Date(f.end).toISOString(),load:stop('load'),unload:stop('unload')}));form.reset();$('notice').textContent='Zlecenie zapisane. Pierwszy odcinek zostanie pobrany automatycznie.';}finally{button.disabled=false;}});};
$('sync').onclick=()=>action(async()=>{await api('sync',{});render(await api('state'));});
$('export').onclick=()=>action(async()=>download('tcog-kopia-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(await api('export'),null,2),'application/json'));
$('orders').onclick=e=>action(async()=>{const pause=e.target.closest('[data-pause]'),plan=e.target.closest('[data-plan]');if(pause){const o=current.orders.find(o=>o.id===pause.dataset.pause);render(await api('pause',{id:o.id,paused:!o.paused}));}if(plan){const o=current.orders.find(o=>o.id===plan.dataset.plan);download('plan-'+o.id+'.txt',`PLAN TRASY — ${o.reference}\nAuto: ${current.vehicle.plate_number||current.vehicle.name}\n\nZAŁADUNEK\n${o.load.address}\nTermin: ${date(o.start)} (czas Polski)\nGPS: ${o.load.lat}, ${o.load.lng}\n\nROZŁADUNEK\n${o.unload.address}\nTermin: ${date(o.end)} (czas Polski)\nGPS: ${o.unload.lat}, ${o.unload.lng}\n\nPlan przygotowany dla dyspozytora do sprawdzenia i wysłania.\n`);}});
$('timezone').textContent='Terminy wpisujesz w strefie przeglądarki: '+Intl.DateTimeFormat().resolvedOptions().timeZone+'. Podgląd i plan pokazują czas Polski.';
api('state').then(render).catch(()=>showLogin());
setInterval(()=>{if(current&&!document.hidden)api('state').then(render).catch(e=>{$('notice').textContent=e.message;});},15000);
